import Link from "next/link";
import PageShell from "@/components/PageShell";
import OrientationBar from "@/components/OrientationBar";
import Badge from "@/components/Badge";
import { coreWorkflow, mvpFeatures, notBuildingYet, startupName } from "@/lib/mock-data";
import { IconArrowUpRight, IconCheck } from "@/components/icons";

export default function ProductPage() {
  return (
    <PageShell>
      <OrientationBar
        where={<>You&rsquo;re in <span className="font-medium text-ink-950">Product</span> — turning a validated idea into a specific MVP.</>}
        accomplished={<>Core user, workflow and MVP scope defined by the Product Architect Agent.</>}
        blocking={<>Nothing — the spec below is ready to hand to the Build Agent.</>}
        next={<>Review the scope, then move to Build to generate your MVP.</>}
      />

      <div className="card p-6 md:p-8">
        <div className="flex items-center justify-between mb-1 flex-wrap gap-2">
          <div className="flex items-center gap-2.5">
            <span className="text-[11px] uppercase tracking-wide text-ink-400 font-medium">MVP specification</span>
          </div>
          <Badge tone="accent">Generated by Product Architect Agent</Badge>
        </div>
        <h2 className="text-[20px] font-semibold text-ink-950 tracking-tight mt-1">{startupName}</h2>

        <div className="mt-6 grid sm:grid-cols-2 gap-6">
          <div>
            <p className="text-[11.5px] font-medium text-ink-400 mb-1">Core user</p>
            <p className="text-[14px] text-ink-900">Sales manager at a small B2B company</p>
          </div>
          <div>
            <p className="text-[11.5px] font-medium text-ink-400 mb-1">Business model</p>
            <p className="text-[14px] text-ink-900">B2B SaaS, monthly subscription</p>
          </div>
        </div>

        <div className="mt-7">
          <p className="text-[11.5px] font-medium text-ink-400 mb-3">Core workflow</p>
          <ol className="space-y-2.5">
            {coreWorkflow.map((step, i) => (
              <li key={step} className="flex items-center gap-3 text-[13.5px] text-ink-800">
                <span className="w-6 h-6 rounded-full bg-ink-950 text-paper text-[11px] font-medium flex items-center justify-center shrink-0">
                  {i + 1}
                </span>
                {step}
                {i < coreWorkflow.length - 1 && <span className="flex-1 h-px bg-ink-100 ml-1" />}
              </li>
            ))}
          </ol>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="card p-6">
          <div className="flex items-center gap-2 mb-1">
            <span className="w-5 h-5 rounded-full bg-good-500 flex items-center justify-center">
              <IconCheck className="w-3 h-3 text-white" />
            </span>
            <h3 className="text-[14.5px] font-semibold text-ink-950">MVP features</h3>
          </div>
          <p className="text-[12px] text-ink-500 mb-4 pl-7">What ships in version one.</p>
          <ul className="space-y-2.5">
            {mvpFeatures.map((f) => (
              <li key={f.label} className="flex items-center gap-2.5 text-[13.5px] text-ink-800">
                <IconCheck className="w-4 h-4 text-good-600 shrink-0" />
                {f.label}
              </li>
            ))}
          </ul>
        </div>

        <div className="card p-6">
          <div className="flex items-center gap-2 mb-1">
            <span className="w-5 h-5 rounded-full bg-ink-200 flex items-center justify-center text-ink-500 text-[11px]">
              ✕
            </span>
            <h3 className="text-[14.5px] font-semibold text-ink-950">Not building yet</h3>
          </div>
          <p className="text-[12px] text-ink-500 mb-4 pl-7">Deliberately deferred to keep the MVP small.</p>
          <ul className="space-y-2.5">
            {notBuildingYet.map((f) => (
              <li key={f.label} className="flex items-center gap-2.5 text-[13.5px] text-ink-400">
                <span className="text-ink-300 w-4 h-4 flex items-center justify-center shrink-0 text-[13px]">✕</span>
                {f.label}
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div className="rounded-2xl border border-ink-100 bg-ink-50/60 px-6 py-5 flex items-center justify-between flex-wrap gap-4">
        <div>
          <p className="text-[13.5px] font-medium text-ink-900">A small MVP ships faster and gets real answers sooner.</p>
          <p className="text-[12px] text-ink-500 mt-0.5">Startup OS deliberately keeps scope tight — you can always expand after launch.</p>
        </div>
        <Link
          href="/build"
          className="inline-flex items-center gap-1.5 rounded-full bg-ink-950 text-paper px-4.5 py-2.5 text-[13px] font-medium hover:bg-ink-800 transition-colors shrink-0"
          style={{ paddingLeft: "1.15rem", paddingRight: "1.15rem" }}
        >
          Proceed to Build
          <IconArrowUpRight className="w-3.5 h-3.5" />
        </Link>
      </div>
    </PageShell>
  );
}
